-- These slots are ordered in the same way as the DAT file, so we can know when GGG adds a new slot and we don't have it mapped
local slotNames = {
	"Weapon 1",
	"Weapon 2",
	"Helmet",
	"Amulet",
	"Ring 1",
	"Ring 2",
	"Gloves",
	"Boots",
	"Belt",
	"Flask 1",
	"Weapon 1 Swap",
	"Weapon 2 Swap",
	"Trinket", -- Trinket not in PoE2
	"Ring 3",
	"Weapon3", -- Legacy
	"Offhand3", -- Legacy
	"Body Armour",
}

local slotsOffsetByX = {
	["Flask 1"] = {
		"Flask 1",
		"Flask 2",
		"Charm 1",
		"Charm 2",
		"Charm 3",
	}
}
local out = io.open("../Data/InventorySlots.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
local i = 1
for inventorySlot in dat("BuildPlannerInventories"):Rows() do
	if i > #slotNames then
		print("Missing inventory slot mapping for '" .. inventorySlot.Inventory.Id .. "'")
	else
		if slotsOffsetByX[slotNames[i]] then
			for xOffset, slotName in ipairs(slotsOffsetByX[slotNames[i]]) do
				out:write('\t["', slotName, '"] = { id = "', inventorySlot.Inventory.Id, '", slot_x = ', xOffset - 1, ' },\n')
			end
		else
			out:write('\t["', slotNames[i], '"] = { id = "', inventorySlot.Inventory.Id, '", slot_x = 0 },\n')
		end
	end
	i = i + 1
end
out:write('}')
out:close()

print("Inventory slots exported.")