-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	["Weapon 1"] = { id = "Weapon1", slot_x = 0 },
	["Weapon 2"] = { id = "Offhand1", slot_x = 0 },
	["Helmet"] = { id = "Helm1", slot_x = 0 },
	["Amulet"] = { id = "Amulet1", slot_x = 0 },
	["Ring 1"] = { id = "Ring1", slot_x = 0 },
	["Ring 2"] = { id = "Ring2", slot_x = 0 },
	["Gloves"] = { id = "Gloves1", slot_x = 0 },
	["Boots"] = { id = "Boots1", slot_x = 0 },
	["Belt"] = { id = "Belt1", slot_x = 0 },
	["Flask 1"] = { id = "Flask1", slot_x = 0 },
	["Flask 2"] = { id = "Flask1", slot_x = 1 },
	["Charm 1"] = { id = "Flask1", slot_x = 2 },
	["Charm 2"] = { id = "Flask1", slot_x = 3 },
	["Charm 3"] = { id = "Flask1", slot_x = 4 },
	["Weapon 1 Swap"] = { id = "Weapon2", slot_x = 0 },
	["Weapon 2 Swap"] = { id = "Offhand2", slot_x = 0 },
	["Trinket"] = { id = "Trinket1", slot_x = 0 },
	["Ring 3"] = { id = "Ring3", slot_x = 0 },
	["Weapon3"] = { id = "Weapon3", slot_x = 0 },
	["Offhand3"] = { id = "Offhand3", slot_x = 0 },
	["Body Armour"] = { id = "BodyArmour1", slot_x = 0 },
}